# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64_vmware"
  config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
  config.vm.hostname = "lesharris.dev"

  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "2048"
  end

  config.vm.network "forwarded_port", guest: 3306, host: 3310

  config.vm.network "private_network", ip: "192.168.10.155"

  config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.provision :shell, :inline => "apt-get -y dist-upgrade"
  config.vm.provision :shell, :inline => "apt-get -y install augeas-lenses"
  config.vm.provision :shell, :inline => "apt-get -y install augeas-tools"
  config.vm.provision :shell, :inline => "apt-get -y install libaugeas-ruby"
  config.vm.provision :shell, :inline => "apt-get -y install libaugeas-dev"
  config.vm.provision :shell, :inline => "apt-get -y install puppet"

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "puppet/manifests"
     puppet.module_path = "puppet/modules"
     puppet.manifest_file  = "main.pp"
  end

  config.vm.synced_folder "D:/dev/MoreVagrant", "/var/www/lesharris"
end
